#!/bin/bash

ngspice circuit.net > result.txt

output=$(python3 parser_ngspice.py)
if [ "$output" = "True" ]; then
    feedback-result success
else
	feedback-result failed
	feedback-msg -em "bouh"
fi
