#!/bin/bash

#getinput "thecode" > student/student_code.py

python3 parser_xml.py
ngspice circuitSpice.cir > result.txt

output=$(python3 parser_ngspice.py)
if [ "$output" = "True" ]; then
    feedback-result success
else
	feedback-result failed
	feedback-msg -em "bouh"
fi
