#!/bin/bash

# get the modified graph by the student
getinput "thegraph" > student/student_graph.xml

# parse the graph to a spice circuit
python3 parser_xml.py student/student_graph.xml

# compute currents and voltages of the circuit 
ngspice circuitSpice.cir > result.txt

# check the solution
output=$(python3 parser_ngspice.py)
if [ "$output" = "True" ]; then
    feedback-result success
else
	feedback-result failed
	feedback-msg -em "bouh"
fi
